import type { PanelSchema } from "@/complements/factory/panelSchema.types";

/**
 * Schema base para vistas AUTOGENERADAS de campañas para AAI.
 * NO se edita a mano en PUI; se rellena por código.
 */
export const AGENT_CAMPAIGNS_CONTEXT_AUTOGENERATED_PANEL_SCHEMA: PanelSchema =
  {
    id: "agentCampaignsContextBase",
    labelKey: "panels.agentCampaignsContextBase.title",
    iconKey: "campaign",
    fsCollection: "Providers",
    fsDocId: "AgentCampaignsContextBase",
    isProvider: true,
    isAgentFDV: true, // <- estos docs sí entran al contexto de AAI
    source: "core",
    stage: "published",
    access: {
      allowedRoles: ["superadmin", "admin"],
    },
    version: 1,
    fields: [
      {
        name: "promotions",
        type: "array",
        groupKey: "promotions",
        element: {
          name: "promotion",
          type: "object",
          collapsible: true,
          fields: [
            // Identificación
            {
              name: "promoId",
              type: "string",
              required: true,
              widget: "input",
            },
            {
              name: "campaignId",
              type: "string",
              required: false,
              widget: "input",
            },
            {
              name: "notificationId",
              type: "string",
              required: false,
              widget: "input",
            },

            // Scopes / tags (filtrado por tipo de AAI)
            {
              name: "scopes",
              type: "array",
              element: {
                name: "scope",
                type: "string",
                widget: "input", // ej: "sales", "support", "cx"
              },
              sortable: true,
            },
            {
              name: "tags",
              type: "array",
              element: {
                name: "tag",
                type: "string",
                widget: "input",
              },
              sortable: true,
            },

            // Contenido
            {
              name: "title",
              type: "string",
              required: true,
              widget: "input",
              translatable: true,
            },
            {
              name: "message",
              type: "text",
              required: true,
              widget: "textarea",
              translatable: true,
            },
            {
              name: "description",
              type: "text",
              required: false,
              widget: "textarea",
              translatable: true,
            },
            {
              name: "category",
              type: "string",
              required: false,
              widget: "input", // "promo", "info", "warning", "system", "other"
            },

            // Audiencia (texto ya digerido para el AAI)
            {
              name: "audienceSummary",
              type: "text",
              required: false,
              widget: "textarea",
            },

            // Ventana de vigencia
            {
              name: "validFrom",
              type: "string",
              required: false,
              widget: "input", // ej: "2025-12-01 10:00"
            },
            {
              name: "validTo",
              type: "string",
              required: false,
              widget: "input",
            },

            // Canales y prioridad
            {
              name: "channels",
              type: "array",
              element: {
                name: "channel",
                type: "string",
                widget: "input", // "inApp", "push", "email", ...
              },
              sortable: true,
            },
            {
              name: "priority",
              type: "select",
              required: false,
              widget: "select",
              options: [
                {
                  value: "low",
                  labelKey:
                    "panels.agentCampaignsContextBase.priority.low",
                },
                {
                  value: "normal",
                  labelKey:
                    "panels.agentCampaignsContextBase.priority.normal",
                },
                {
                  value: "high",
                  labelKey:
                    "panels.agentCampaignsContextBase.priority.high",
                },
              ],
            },

            // Flag de activación
            {
              name: "isActive",
              type: "boolean",
              required: false,
            },
          ],
        },
        sortable: true,
      },
    ],
  };

/**
 * Vistas concretas por tipo de contexto de campañas para AAI.
 * OJO: aquí ya usamos los docIds que quieres para sources[]:
 *
 *   sources={["SalesCampaigns", "branding", "settings"]}
 */

export const AGENT_SALES_CAMPAIGNS_PANEL_SCHEMA: PanelSchema = {
  ...AGENT_CAMPAIGNS_CONTEXT_AUTOGENERATED_PANEL_SCHEMA,
  id: "SalesCampaigns", // nombre lógico del provider para AAI
  labelKey: "panels.SalesCampaigns.title",
  iconKey: "sell",
  fsDocId: "SalesCampaigns",
};

export const AGENT_INFO_CAMPAIGNS_PANEL_SCHEMA: PanelSchema = {
  ...AGENT_CAMPAIGNS_CONTEXT_AUTOGENERATED_PANEL_SCHEMA,
  id: "InfoCampaigns",
  labelKey: "panels.InfoCampaigns.title",
  iconKey: "info",
  fsDocId: "InfoCampaigns",
};

export const AGENT_SUPPORT_CAMPAIGNS_PANEL_SCHEMA: PanelSchema = {
  ...AGENT_CAMPAIGNS_CONTEXT_AUTOGENERATED_PANEL_SCHEMA,
  id: "SupportCampaigns",
  labelKey: "panels.SupportCampaigns.title",
  iconKey: "support",
  fsDocId: "SupportCampaigns",
};

export const AGENT_CX_CAMPAIGNS_PANEL_SCHEMA: PanelSchema = {
  ...AGENT_CAMPAIGNS_CONTEXT_AUTOGENERATED_PANEL_SCHEMA,
  id: "CxCampaigns",
  labelKey: "panels.CxCampaigns.title",
  iconKey: "cx", // pon el iconKey que ya uses para CX
  fsDocId: "CxCampaigns",
};

export const AGENT_OTHER_CAMPAIGNS_PANEL_SCHEMA: PanelSchema = {
  ...AGENT_CAMPAIGNS_CONTEXT_AUTOGENERATED_PANEL_SCHEMA,
  id: "OtherCampaigns",
  labelKey: "panels.OtherCampaigns.title",
  iconKey: "campaign",
  fsDocId: "OtherCampaigns",
};
