import type { PanelSchemasRegistry } from '../panelSchema.types';
import { BRANDING_PANEL_SCHEMA } from './branding.schema';
import { SETTINGS_PANEL_SCHEMA } from './settings.schema';
import { PWA_PANEL_SCHEMA } from './pwa.schema'
import { NOTIFICATIONS_PANEL_SCHEMA } from './notifications.schema'
import { STRATEGIES_PANEL_SCHEMA } from './strategy.schema';
import { AUDIENCES_PANEL_SCHEMA } from './audience.schema';
import { PRODUCTS_PANEL_SCHEMA } from './products.schema';
import { SERVICES_PANEL_SCHEMA } from './services.schema';

import { ENV_PANEL_SCHEMA } from './env.schema';

import {
  AGENT_CAMPAIGNS_CONTEXT_AUTOGENERATED_PANEL_SCHEMA,
  AGENT_SALES_CAMPAIGNS_PANEL_SCHEMA,
  AGENT_INFO_CAMPAIGNS_PANEL_SCHEMA,
  AGENT_SUPPORT_CAMPAIGNS_PANEL_SCHEMA,
  AGENT_CX_CAMPAIGNS_PANEL_SCHEMA,
  AGENT_OTHER_CAMPAIGNS_PANEL_SCHEMA,
} from "./agentCampaignsContext.schema";

export const PANEL_SCHEMAS: PanelSchemasRegistry = {
  branding: BRANDING_PANEL_SCHEMA,
  settings: SETTINGS_PANEL_SCHEMA,
  pwa: PWA_PANEL_SCHEMA,
  notifications: NOTIFICATIONS_PANEL_SCHEMA,
  strategies: STRATEGIES_PANEL_SCHEMA,
  audiences: AUDIENCES_PANEL_SCHEMA,

  services: SERVICES_PANEL_SCHEMA,
  products: PRODUCTS_PANEL_SCHEMA,

  env: ENV_PANEL_SCHEMA,

  // Autogenerados para contexto de Agentes AI: NO TOCAR//
  //***********************************************//
  SalesCampaigns: AGENT_SALES_CAMPAIGNS_PANEL_SCHEMA,   //***/
  InfoCampaigns: AGENT_INFO_CAMPAIGNS_PANEL_SCHEMA,   //***/
  SupportCampaigns: AGENT_SUPPORT_CAMPAIGNS_PANEL_SCHEMA,   //***/
  CxCampaigns: AGENT_CX_CAMPAIGNS_PANEL_SCHEMA,   //***/
  OtherCampaigns: AGENT_OTHER_CAMPAIGNS_PANEL_SCHEMA,   //***/
  //***********************************************//
};